config/routes.rb
Rails.application.routes.draw do

		root 'pages#index'
		resources:reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@latest_reservations = Reservation.last(5)
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def index
		@latest_reservations = Reservation.all
	end
	def create
		@reservation = Reservation.new
		@reservation.first_name = params[:reservation][:first_name]
		@reservation.last_name = params[:reservation][:last_name]
		@reservation.contact_number = params[:reservation][:contact_number]
		@reservation.email = params[:reservation][:email]
		@reservation.room_number = params[:reservation][:room_number]
		@reservation.number_of_people = params[:reservation][:number_of_people]
		@reservation.start_date = params[:reservation][:start_date]
		@reservation.end_date = params[:reservation][:end_date]
		@reservation.save
		redirect_to :action => :index
 	end
	def new
		@reservation = Reservation.new
	end
	def show
		@reservation = Reservation.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotelreservation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<html>
<head>
<title>
List of reservations
</title>
</head>
<body>
<h1>List of Reservations</h1>
<table class = "table">
	<thead>
		<tr>
			<td>E-mail</td>
			<td>Room Number</td>
			<td>Number of People</td>
			<td>Start Date</td>
			<td>End Date</td>
		</tr>
	</thead>
	<tbody>
		<% @latest_reservations.each do |latest_reservation| %>
		<tr>
			<td><%= latest_reservation.email %></td>
			<td><%= latest_reservation.room_number %></td>
			<td><%= latest_reservation.number_of_people %></td>
			<td><%= latest_reservation.start_date %></td>
			<td><%= latest_reservation.end_date %></td>
			<td><%= link_to latest_reservation.first_name, latest_reservation %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Show all reservations', reservations_path %>
</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for reservation do |f| %>
	<%= f.label :first_name, 'First Name' %>
	<%= f.text_field :first_name %>
	<br />
	<%= f.label :last_name, 'Last Name' %>
	<%= f.text_field :last_name %>
	<br />
	<%= f.label :contact_number, 'Contact Number' %>
	<%= f.text_field :contact_number %>
	<br />
	<%= f.label :room_number, 'Room Number' %>
	<%= f.text_field :room_number %>
	<br />
	<%= f.label :email, 'E-mail' %>
	<%= f.text_field :email %>
	<br />
	<%= f.label :number_of_people, 'Number of People' %>
	<%= f.text_field :number_of_people %>
	<br />
	<%= f.label :start_date,'Start Date' %>
	<%= f.date_field :start_date %>
	<br />
	<%= f.label :end_date,'End Date' %>
	<%= f.date_field :end_date %>
	<br />
	<%= f.submit 'Submit' %>
<% end %>

app/views/reservations/index.html.erb
<html>
<head>
<title>
List of reservations
</title>
</head>
<body>
<h1>List of Reservations</h1>
<table class = "table">
	<thead>
		<tr>
			<td>E-mail</td>
			<td>Room Number</td>
			<td>Number of People</td>
			<td>Start Date</td>
			<td>End Date</td>
		</tr>
	</thead>
	<tbody>
		<% @latest_reservations.each do |latest_reservation| %>
		<tr>
			<td><%= latest_reservation.email %></td>
			<td><%= latest_reservation.room_number %></td>
			<td><%= latest_reservation.number_of_people %></td>
			<td><%= latest_reservation.start_date %></td>
			<td><%= latest_reservation.end_date %></td>
			<td><%= link_to latest_reservation.first_name, latest_reservation %></td>
		</tr>
		<% end %>
	</tbody>
</table>
	<%= link_to 'Create New Reservation', new_reservation_path %>
</body>
</html>

app/views/reservations/new.html.erb
<html>
<head><title>Create reservatiom</title></head>
<h1>NEW RESERVATION</h1>
<body>
<%= render :partial => "reservations/form", locals: {reservation: @reservation} %>

</body>
</html>

app/views/reservations/show.html.erb
<h1><%= @reservation.first_name %> <%= @reservation.last_name %>'s Reservation</h1>
<p><%= debug @reservation %> <p>
<%= link_to 'Show all reservations', reservations_path %>